// generated by stringer -type=SampleType; DO NOT EDIT

package sampletypes

import "fmt"

const _SampleType_name = "NoneHTTPHeaderBrowserExtensionNewClientTokenDNSQuery"

var _SampleType_index = [...]uint8{0, 4, 14, 30, 44, 52}

func (i SampleType) String() string {
	if i < 0 || i >= SampleType(len(_SampleType_index)-1) {
		return fmt.Sprintf("SampleType(%d)", i)
	}
	return _SampleType_name[_SampleType_index[i]:_SampleType_index[i+1]]
}
