// generated by stringer -type=SampleOrigin; DO NOT EDIT

package sampleorigins

import "fmt"

const _SampleOrigin_name = "NoneClientCentral"

var _SampleOrigin_index = [...]uint8{0, 4, 10, 17}

func (i SampleOrigin) String() string {
	if i < 0 || i >= SampleOrigin(len(_SampleOrigin_index)-1) {
		return fmt.Sprintf("SampleOrigin(%d)", i)
	}
	return _SampleOrigin_name[_SampleOrigin_index[i]:_SampleOrigin_index[i+1]]
}
