// generated by stringer -type=ConnectionState; DO NOT EDIT

package service

import "fmt"

const _ConnectionState_name = "InitServiceInitServiceStartTestUpBackoffWrongProtocolFailedNotConfiguredTestFailedEnded"

var _ConnectionState_index = [...]uint8{0, 4, 15, 27, 31, 33, 40, 53, 59, 72, 82, 87}

func (i ConnectionState) String() string {
	if i < 0 || i+1 >= ConnectionState(len(_ConnectionState_index)) {
		return fmt.Sprintf("ConnectionState(%d)", i)
	}
	return _ConnectionState_name[_ConnectionState_index[i]:_ConnectionState_index[i+1]]
}
