// generated by stringer -type=UpdateResult; DO NOT EDIT

package client

import "fmt"

const _UpdateResult_name = "UpdateErrorUpdateSuccess"

var _UpdateResult_index = [...]uint8{0, 11, 24}

func (i UpdateResult) String() string {
	if i < 0 || i+1 >= UpdateResult(len(_UpdateResult_index)) {
		return fmt.Sprintf("UpdateResult(%d)", i)
	}
	return _UpdateResult_name[_UpdateResult_index[i]:_UpdateResult_index[i+1]]
}
